### ISSUE TITLE
I need 24/7

### ISSUE THREAD

**Issue by Abhilash2008New** [Major-Thrust/Discordjs-MusicBot#10]
Make a 24/7 in VC commmand Please!

**Comment by NithishCodez** [comment]
Noted, Will be fulfilled in the next update

**Comment by Abhilash2008New** [comment]
> Noted, Will be fulfilled in the next update

 Sir Thank you, great coding skills you have! And also please put radio if possible. High expectations from you sir!

**Comment by NithishCodez** [comment]
Thanks 😁, And yes raido will also be added, Next update also has web dashboards, its gonna be huge ;)

**Comment by Abhilash2008New** [comment]
> Thanks 😁, And yes raido will also be added, Next update also has web dashboards, its gonna be huge ;)
When will it come waiting for it!
