### ISSUE TITLE
Resume Error

### ISSUE THREAD

**Issue by skibop** [Major-Thrust/Discordjs-MusicBot#13]
Does not resume music! No errors in console, but still does not resume music..

**Comment by NithishCodez** [comment]
Known issue, Issuing a fix in couple days, In a new video

**Comment by skibop** [comment]
Ok cool, keep up the good work

**Comment by skibop** [comment]
Was able to fix.. 
Instead of just queue.connection.dispatcher.resume();

Simply do:

        queue.connection.dispatcher.pause();
        queue.connection.dispatcher.resume();
        queue.connection.dispatcher.pause();
        queue.connection.dispatcher.resume();
